services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: careguide_api
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DatabaseConnection: Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - care-guide-api-network

  db:
    image: postgres:18
    container_name: careguide_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: careguide
      POSTGRES_DB: careguide
      PGDATA: /var/lib/postgresql/18/docker
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - '5434:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d careguide']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - care-guide-api-network

  db_test:
    image: postgres:18
    container_name: careguide_db_tests
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: careguide
      POSTGRES_DB: careguide_tests
      PGDATA: /var/lib/postgresql/18/docker
    volumes:
      - postgres-tests-data:/var/lib/postgresql
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d careguide_tests']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - care-guide-api-network

networks:
  care-guide-api-network:
    driver: bridge

volumes:
  postgres-data:
  postgres-tests-data:
