services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: careguide_api
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DatabaseConnection=Host=careguide_db;Port=5432;Database=careguide;Username=postgres;Password=careguide
    depends_on:
      - db
    networks:
      - care-guide-api-network

  db:
    image: postgres
    container_name: careguide_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: careguide
      POSTGRES_DB: careguide
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - care-guide-api-network

  db_test:
    image: postgres
    container_name: careguide_db_tests
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: careguide
      POSTGRES_DB: careguide_tests
    volumes:
      - postgres-tests-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - care-guide-api-network

networks:
  care-guide-api-network:
    driver: bridge

volumes:
  postgres-data:
  postgres-tests-data:
