name: CI Pipeline

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Prevent direct commits to master
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          echo "Direct commits to 'master' are not allowed. Use pull requests to 'development'."
          exit 1

      - name: Prevent pull requests to master
        if: github.event_name == 'pull_request' && github.base_ref == 'master'
        run: |
          echo "Pull requests to 'master' are not allowed. Please target 'development'."
          exit 1

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release
