name: CI Pipeline

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - master

jobs:
  prevent-master-push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Block direct commits to master
        run: |
          echo "Commits diretos na branch 'master' não são permitidos."
          exit 1

  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release
