name: ".NET 9 Build Check"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Validate Dockerfile (build image)
        run: docker build -t careguide_api:ci -f Dockerfile .

      - name: Validate docker-compose syntax
        run: docker compose -f docker-compose.yml config

      - name: Test docker-compose up/down
        run: |
          docker compose -f docker-compose.yml up -d
          sleep 10
          docker compose -f docker-compose.yml down
