name: Docker Validation Pipeline

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

jobs:
  docker-build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker Image
        run: docker build -t careguide_api:latest -f Dockerfile .

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Stop Docker Compose
        run: docker-compose down
