name: Docker Validation Pipeline

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - master

jobs:
  prevent-master-push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Block direct commits to master
        run: |
          echo "Commits diretos na branch 'master' não são permitidos."
          exit 1

  docker-build-and-run:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker Image
        run: docker build -t careguide_api:latest -f Dockerfile .

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Stop Docker Compose
        run: docker-compose down
