name: Docker Validation Pipeline

on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - master

jobs:
  docker-build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Prevent direct commits to master
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          echo "Direct commits to 'master' are not allowed. Use pull requests to 'development'."
          exit 1

      - name: Prevent pull requests to master
        if: github.event_name == 'pull_request' && github.base_ref == 'master'
        run: |
          echo "Pull requests to 'master' are not allowed. Please target 'development'."
          exit 1

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Check Docker and Docker Compose versions
        run: |
          docker --version
          docker-compose --version || echo "Docker Compose not found"

      - name: Build Docker Image
        run: docker build -t careguide_api:latest -f Dockerfile .

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Stop Docker Compose
        run: docker-compose down
